########### Aliases ##########

Source: https://www.marquette.edu/high-performance-computing/bashrc.php

Aliases can be added directly to .bashrc, however, it is common practice to add aliases to a file called .bash_aliases, then load .bash_aliases into .bashrc like so:

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

An alias can be defined using the following syntax:

alias <aliasname>="<command>"
 

Common aliases include:
alias ll="ls -l"
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'
alias la='ls -a'
alias rm='rm -i' #-i prompts user before deletion
alias cp='cp -i' #-i prompts user before overwriting

Another alias that may be helpful is activating Python virtual environments. 
Say you have a multiple virtual environments you want to switch between quickly. Instead of loading the environments by default in .bashrc, you could create aliases to activate them for you. 

alias env1="source ~/project1/env/activate"
alias env2="source ~/project2/env/activate"
alias env3="source ~/project3/env/activate"

Now if you want to quickly switch between environments you can issue the following commands:

deactivate # deactivate the currently loaded environment
env2 #activate environment for project2


